# -*- coding: utf-8 -*-
"""ABSA_Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cniTxnuittZShx3Flj8SVVCFgukKw5oY
"""

import pandas as pd
import numpy as np
import torch
import transformers
from tqdm.auto import tqdm
import sklearn

import os
import zipfile
import torch
from google.colab import drive
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# 1. Mount Google Drive
drive.mount('/content/drive')

# 2. Definisikan path file ZIP dan tujuan ekstraksi
zip_path_aspect = '/content/drive/MyDrive/model_absa/aspect_model.zip'
zip_path_sentiment = '/content/drive/MyDrive/model_absa/sentiment_model.zip'
extract_path_aspect = '/content/aspect_model/'
extract_path_sentiment = '/content/sentiment_model/'

# 3. Fungsi untuk mengekstrak file ZIP
def extract_zip(zip_path, extract_to):
    if os.path.exists(zip_path):
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(extract_to)
        print(f"Berhasil mengekstrak {zip_path} ke {extract_to}")
    else:
        print(f"Error: File {zip_path} tidak ditemukan.")

# Ekstrak kedua model
extract_zip(zip_path_aspect, extract_path_aspect)
extract_zip(zip_path_sentiment, extract_path_sentiment)

# 6. Set device (GPU jika tersedia, jika tidak gunakan CPU)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Menggunakan device: {device}")

# 5 & 7. Muat model dan tokenizer, lalu pindahkan ke device
print("Loading Aspect Model...")
aspect_tokenizer = AutoTokenizer.from_pretrained(extract_path_aspect)
aspect_model = AutoModelForSequenceClassification.from_pretrained(extract_path_aspect).to(device)

print("Loading Sentiment Model...")
sentiment_tokenizer = AutoTokenizer.from_pretrained(extract_path_sentiment)
sentiment_model = AutoModelForSequenceClassification.from_pretrained(extract_path_sentiment).to(device)

# 8. Ubah model ke mode evaluasi
aspect_model.eval()
sentiment_model.eval()

# 9. Konfirmasi
print("\n--- Konfirmasi ---")
print("Semua model dan tokenizer berhasil dimuat dan siap digunakan.")
print(f"Aspect Model Device: {next(aspect_model.parameters()).device}")
print(f"Sentiment Model Device: {next(sentiment_model.parameters()).device}")

# Tentukan path file dataset
# Berdasarkan daftar file, tersedia /content/test_dataset.csv
dataset_path = '/content/test_dataset.csv'

try:
    # Membaca dataset
    df = pd.read_csv(dataset_path)

    # Menampilkan informasi verifikasi
    print(f"Jumlah total data: {len(df)}")
    print(f"Nama kolom: {df.columns.tolist()}")
    print("\nLima baris pertama dataset:")
    display(df.head())

except FileNotFoundError:
    print(f"Error: File {dataset_path} tidak ditemukan. Pastikan file sudah diunggah atau path sudah benar.")

import torch
from tqdm.auto import tqdm

# Mapping label ID ke nama aspek (sesuaikan jika label map Anda berbeda)
# Biasanya model menyimpan ini di config.id2label
label_map = aspect_model.config.id2label

def predict_aspect(text):
    # Tokenisasi teks input
    inputs = aspect_tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=128).to(device)

    # Lakukan inferensi tanpa menghitung gradien
    with torch.no_grad():
        outputs = aspect_model(**inputs)

    # Ambil index dengan logit tertinggi
    probs = torch.nn.functional.softmax(outputs.logits, dim=-1)
    predicted_class_id = torch.argmax(probs, dim=-1).item()

    # Kembalikan nama label dari mapping
    return label_map[predicted_class_id]

# Terapkan fungsi prediksi ke kolom Reviews
tqdm.pandas(desc="Predicting Aspects")
df['Predicted_Aspect'] = df['Reviews'].progress_apply(predict_aspect)

# Tampilkan hasil untuk verifikasi
print("\nPrediksi selesai. Berikut 5 data pertama dengan kolom Predicted_Aspect:")
display(df[['Reviews', 'Aspect', 'Predicted_Aspect']].head())

import torch
from tqdm.auto import tqdm
from sklearn.metrics import classification_report

# Mapping manual berdasarkan output sebelumnya (LABEL_0=Positif, LABEL_1=Negatif)
sentiment_mapping = {'LABEL_0': 'Positif', 'LABEL_1': 'Negatif'}

def predict_sentiment(text):
    inputs = sentiment_tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=128).to(device)
    with torch.no_grad():
        outputs = sentiment_model(**inputs)
    predicted_class_id = torch.argmax(outputs.logits, dim=-1).item()
    raw_label = sentiment_model.config.id2label[predicted_class_id]
    return sentiment_mapping.get(raw_label, raw_label)

# Jalankan ulang prediksi
tqdm.pandas(desc="Predicting Sentiment")
df['Predicted_Sentiment'] = df['Reviews'].progress_apply(predict_sentiment)

# Tampilkan hasil verifikasi
print("\nHasil Prediksi Sentiment (Mapped):")
display(df[['Reviews', 'Sentiment', 'Predicted_Sentiment']].head())

# Tampilkan Classification Report
print("\nClassification Report for Sentiment:")
print(classification_report(df['Sentiment'], df['Predicted_Sentiment']))

print("\nClassification Report for Aspect:")
print(classification_report(df['Aspect'], df['Predicted_Aspect']))

# 1. Pilih kolom yang diminta untuk hasil akhir
result_cols = {
    'Reviews': df['Reviews'],
    'Actual Aspect': df['Aspect'],
    'Predicted Aspect': df['Predicted_Aspect'],
    'Actual Sentiment': df['Sentiment'],
    'Predicted Sentiment': df['Predicted_Sentiment']
}
df_results = pd.DataFrame(result_cols)

# 2. Simpan seluruh hasil ke CSV
df_results.to_csv('absa_pipeline_result.csv', index=False)
print("Berhasil menyimpan seluruh hasil ke 'absa_pipeline_result.csv'")

# 3. Filter data yang salah diprediksi (Misclassified)
# Salah diprediksi jika Aspect tidak sama ATAU Sentiment tidak sama
misclassified_mask = (df_results['Actual Aspect'] != df_results['Predicted Aspect']) | \
                     (df_results['Actual Sentiment'] != df_results['Predicted Sentiment'])

df_misclassified = df_results[misclassified_mask]

# 4. Simpan data yang salah diprediksi ke CSV
df_misclassified.to_csv('absa_pipeline_misclassified.csv', index=False)
print(f"Berhasil menyimpan {len(df_misclassified)} data yang salah diprediksi ke 'absa_pipeline_misclassified.csv'")

# Tampilkan cuplikan data misclassified
if not df_misclassified.empty:
    print("\nCuplikan data yang salah diprediksi:")
    display(df_misclassified.head())

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

def plot_and_save_cm(y_true, y_pred, title, filename):
    # Menghitung confusion matrix
    cm = confusion_matrix(y_true, y_pred)
    labels = sorted(list(set(y_true) | set(y_pred)))

    # Membuat plot
    fig, ax = plt.subplots(figsize=(10, 8))
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)
    disp.plot(cmap=plt.cm.Blues, ax=ax, xticks_rotation='vertical')

    plt.title(title)
    plt.tight_layout()

    # Simpan ke file
    plt.savefig(filename)
    plt.show()
    print(f"Confusion Matrix disimpan sebagai {filename}")

# 1. Plot Confusion Matrix Aspect
plot_and_save_cm(
    df['Aspect'],
    df['Predicted_Aspect'],
    "Confusion Matrix: Aspect Classification",
    "confusion_matrix_aspect.png"
)

# 2. Plot Confusion Matrix Sentiment
plot_and_save_cm(
    df['Sentiment'],
    df['Predicted_Sentiment'],
    "Confusion Matrix: Sentiment Classification",
    "confusion_matrix_sentiment.png"
)

def predict_single_review(text):
    # Prediksi Aspek
    aspect = predict_aspect(text)

    # Prediksi Sentimen
    sentiment = predict_sentiment(text)

    print(f"--- Hasil Analisis ---")
    print(f"Kalimat: \"{text}\"")
    print(f"Aspek  : {aspect}")
    print(f"Sentimen: {sentiment}")
    print(f"----------------------")

# Silakan ganti kalimat di bawah ini untuk mencoba
input_teks = "suka banget sama servernya tidak ada delay sama sekali, tapi kurang suka sama gameplaynya"
predict_single_review(input_teks)

import re

def predict_multiple_aspect_sentiment(text):
    results = []
    # Simple splitting based on common conjunctions to identify potential separate clauses
    # This is a heuristic approach to handle multiple aspect/sentiment expressions
    # For more robust Aspect-Based Sentiment Analysis, dedicated libraries or more complex models are typically used.
    sentences = re.split(r'(?i)\b(tapi|dan|namun|tetapi)\b[,.]*', text)
    sentences = [s.strip() for s in sentences if s.strip()]

    # If splitting yields only one segment, treat it as a single review
    if not sentences:
        return []
    elif len(sentences) == 1:
        aspect = predict_aspect(text)
        sentiment = predict_sentiment(text)
        results.append({
            "text_segment": text,
            "aspect": aspect,
            "sentiment": sentiment
        })
    else:
        for segment in sentences:
            if segment:
                aspect = predict_aspect(segment)
                sentiment = predict_sentiment(segment)
                results.append({
                    "text_segment": segment,
                    "aspect": aspect,
                    "sentiment": sentiment
                })
    return results

# Example usage with the previous input, which has two distinct sentiments/aspects
input_teks_multiple = "suka banget sama servernya tidak ada delay sama sekali, tapi gameplaynya kurang bagus"
predictions = predict_multiple_aspect_sentiment(input_teks_multiple)

print(f"--- Hasil Analisis Multi-Aspek & Multi-Sentimen ---")
print(f"Original Kalimat: \"{input_teks_multiple}\"")
for i, pred in enumerate(predictions):
    print(f"  Analisis #{i+1}:")
    print(f"    Segmen Teks: \"{pred['text_segment']}\"")
    print(f"    Aspek      : {pred['aspect']}")
    print(f"    Sentimen   : {pred['sentiment']}")
print(f"--------------------------------------------------")

# Another example with 'dan' (and)
input_teks_multiple_2 = "Game ini merusak saya, saya jadi lupa makan dan tidak punya teman"
predictions_2 = predict_multiple_aspect_sentiment(input_teks_multiple_2)

print(f"\n--- Hasil Analisis Multi-Aspek & Multi-Sentimen ---")
print(f"Original Kalimat: \"{input_teks_multiple_2}\"")
for i, pred in enumerate(predictions_2):
    print(f"  Analisis #{i+1}:")
    print(f"    Segmen Teks: \"{pred['text_segment']}\"")
    print(f"    Aspek      : {pred['aspect']}")
    print(f"    Sentimen   : {pred['sentiment']}")
print(f"--------------------------------------------------")

# Example for a single sentence to ensure it still works correctly
input_teks_single_case = "Game ini memiliki cerita yang bagus sekali."
predictions_single_case = predict_multiple_aspect_sentiment(input_teks_single_case)

print(f"\n--- Hasil Analisis Multi-Aspek & Multi-Sentimen ---")
print(f"Original Kalimat: \"{input_teks_single_case}\"")
for i, pred in enumerate(predictions_single_case):
    print(f"  Analisis #{i+1}:")
    print(f"    Segmen Teks: \"{pred['text_segment']}\"")
    print(f"    Aspek      : {pred['aspect']}")
    print(f"    Sentimen   : {pred['sentiment']}")
print(f"--------------------------------------------------")