# -*- coding: utf-8 -*-
"""AspectClassification8020.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eV8SlhyyjmzTDv5c_xMEzc4nQlFN4jyJ
"""

import pandas as pd

# Memuat dataset CSV
df = pd.read_csv('/content/SteamDatasetTiga.csv')

# Menampilkan 5 baris pertama dari dataset
df.head()

# Total aspect yang terbagi
print("Total Aspek:")
print(df['Aspect'].value_counts())

print("\nTotal Sentimen:")
# Sentiment positif
positive_sentiment = df[df['Sentiment'] == 'Positif'].shape[0]
print(f"Sentimen Positif: {positive_sentiment}")

# Sentiment negatif
negative_sentiment = df[df['Sentiment'] == 'Negatif'].shape[0]
print(f"Sentimen Negatif: {negative_sentiment}")

sentiment_distribution = pd.crosstab(df['Aspect'], df['Sentiment'])
print("Distribusi Sentimen per Aspek:")
print(sentiment_distribution)

import matplotlib.pyplot as plt

# Memastikan kolom sentimen ada, jika tidak ada, tambahkan dengan 0
# Ini penting jika ada aspek yang tidak memiliki 'Negatif' atau 'Positif'
for col in ['Positif', 'Negatif']: # Assuming only these two sentiments for visualization
    if col not in sentiment_distribution.columns:
        sentiment_distribution[col] = 0

# Buat bar chart stacked
sentiment_distribution[['Positif', 'Negatif']].plot(kind='bar', stacked=True, figsize=(10, 6))
plt.title('Distribusi Sentimen per Aspek')
plt.xlabel('Aspek')
plt.ylabel('Jumlah')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Sentimen')
plt.tight_layout()
plt.show()

from sklearn.model_selection import train_test_split

# Memisahkan fitur (X) dan label (y)
X = df.drop(['Aspect', 'Sentiment'], axis=1) # Sesuaikan kolom fitur Anda
y_aspect = df['Aspect'] # Target untuk stratifikasi aspek

# Pertama, bagi data menjadi training (80%) dan temporary (20%) datasets
X_train, X_temp, y_aspect_train, y_aspect_temp = train_test_split(
    X, y_aspect, test_size=0.2, random_state=42, stratify=y_aspect
)

# Selanjutnya, bagi data temporary (20%) menjadi validation (10%) dan testing (10%) datasets
# Karena X_temp adalah 20% dari total, kita ambil 0.5 dari X_temp untuk mendapatkan 10% dari total
X_val, X_test, y_aspect_val, y_aspect_test = train_test_split(
    X_temp, y_aspect_temp, test_size=0.5, random_state=42, stratify=y_aspect_temp
)

print(f"Ukuran data training: {X_train.shape[0]} ({round(X_train.shape[0]/df.shape[0]*100)}%)")
print(f"Ukuran data validasi: {X_val.shape[0]} ({round(X_val.shape[0]/df.shape[0]*100)}%)")
print(f"Ukuran data testing: {X_test.shape[0]} ({round(X_test.shape[0]/df.shape[0]*100)}%)\n")

print("Distribusi 'Aspect' dalam set pelatihan:")
print(y_aspect_train.value_counts(normalize=True))
print("\nDistribusi 'Aspect' dalam set validasi:")
print(y_aspect_val.value_counts(normalize=True))
print("\nDistribusi 'Aspect' dalam set pengujian:")
print(y_aspect_test.value_counts(normalize=True))

# Instal library transformers jika belum terinstal
!pip install transformers

from transformers import AutoTokenizer

# Load pre-trained IndoBERT tokenizer
tokenizer = AutoTokenizer.from_pretrained("indobenchmark/indobert-base-p1")

# Tokenisasi data 'Reviews' untuk set pelatihan, validasi, dan pengujian
# Pastikan kolom 'Reviews' ada di X_train, X_val, X_test
tokenized_train = tokenizer(
    list(X_train['Reviews'].astype(str)), # Mengubah ke list string
    truncation=True,
    padding=True,
    max_length=128,
    return_tensors="pt"
)

tokenized_val = tokenizer(
    list(X_val['Reviews'].astype(str)), # Mengubah ke list string
    truncation=True,
    padding=True,
    max_length=128,
    return_tensors="pt"
)

tokenized_test = tokenizer(
    list(X_test['Reviews'].astype(str)), # Mengubah ke list string
    truncation=True,
    padding=True,
    max_length=128,
    return_tensors="pt"
)

print("Tokenisasi data training selesai. Contoh:")
print(tokenized_train['input_ids'][0])
print("Tokenisasi data validasi selesai. Contoh:")
print(tokenized_val['input_ids'][0])
print("Tokenisasi data testing selesai. Contoh:")
print(tokenized_test['input_ids'][0])

import torch
from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import numpy as np

# 1. Mengonversi label 'Aspect' ke ID numerik
# Dapatkan semua label unik dari kolom 'Aspect' di seluruh dataset asli
all_aspect_labels = df['Aspect'].unique()
label_list = sorted(all_aspect_labels) # Urutkan untuk konsistensi

label_to_id = {label: i for i, label in enumerate(label_list)}
id_to_label = {i: label for i, label in enumerate(label_list)}

print(f"Label to ID mapping: {label_to_id}")
print(f"ID to Label mapping: {id_to_label}")

# Ubah label 'Aspect' dari y_aspect_train, y_aspect_val, y_aspect_test menjadi ID numerik
y_train_labels = y_aspect_train.map(label_to_id)
y_val_labels = y_aspect_val.map(label_to_id)
y_test_labels = y_aspect_test.map(label_to_id)

# 2. Buat PyTorch Dataset
class AspectDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = AspectDataset(tokenized_train, y_train_labels.values)
val_dataset = AspectDataset(tokenized_val, y_val_labels.values)
test_dataset = AspectDataset(tokenized_test, y_test_labels.values)

# 3. Muat model IndoBERT untuk klasifikasi urutan
model = AutoModelForSequenceClassification.from_pretrained(
    "indobenchmark/indobert-base-p1",
    num_labels=len(label_list),
    id2label=id_to_label,
    label2id=label_to_id,
    ignore_mismatched_sizes=True # Tambahkan baris ini
)

# 4. Definisikan metrik komputasi
def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='weighted')
    acc = accuracy_score(labels, preds)
    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

# 5. Konfigurasi argumen pelatihan
training_args = TrainingArguments(
    output_dir='./results_aspect_classification',
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs',
    logging_steps=10,
    eval_strategy="epoch", # Lakukan evaluasi setiap epoch
    save_strategy="epoch",      # Simpan model setiap epoch
    load_best_model_at_end=True, # Ganti load_best_model_as_init_checkpoint menjadi load_best_model_at_end
    metric_for_best_model="f1", # Metrik untuk memilih model terbaik
    greater_is_better=True
)

# 6. Inisialisasi Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

# 7. Mulai pelatihan
print("Memulai fine-tuning model...")
trainer.train()
print("Fine-tuning selesai!")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# =====================================================
# EVALUASI MODEL ASPECT CLASSIFICATION
# =====================================================

print("=" * 60)
print("EVALUASI MODEL ASPECT CLASSIFICATION")
print("=" * 60)

# Melakukan prediksi pada data test
predictions = trainer.predict(test_dataset)

# Label aktual
y_true = predictions.label_ids

# Label hasil prediksi
y_pred = np.argmax(predictions.predictions, axis=1)

# =====================================================
# METRIK EVALUASI
# =====================================================

accuracy = accuracy_score(y_true, y_pred)

precision = precision_score(
    y_true,
    y_pred,
    average="weighted",
    zero_division=0
)

recall = recall_score(
    y_true,
    y_pred,
    average="weighted",
    zero_division=0
)

f1 = f1_score(
    y_true,
    y_pred,
    average="weighted",
    zero_division=0
)

print(f"\nAccuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1-Score : {f1:.4f}")

# =====================================================
# CONVERT LABEL ID KE NAMA ASPECT
# =====================================================

actual_labels = [id_to_label[i] for i in y_true]
predicted_labels = [id_to_label[i] for i in y_pred]

# =====================================================
# CLASSIFICATION REPORT
# =====================================================

print("\n")
print("=" * 60)
print("CLASSIFICATION REPORT")
print("=" * 60)

print(
    classification_report(
        actual_labels,
        predicted_labels,
        labels=label_list,
        target_names=label_list,
        digits=4,
        zero_division=0
    )
)

# Simpan classification report ke CSV
report = classification_report(
    actual_labels,
    predicted_labels,
    labels=label_list,
    target_names=label_list,
    output_dict=True,
    zero_division=0
)

report_df = pd.DataFrame(report).transpose()

report_df.to_csv(
    "classification_report_aspect.csv",
    index=True
)

# =====================================================
# CONFUSION MATRIX
# =====================================================

cm = confusion_matrix(
    actual_labels,
    predicted_labels,
    labels=label_list
)

plt.figure(figsize=(10,8))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=label_list,
    yticklabels=label_list
)

plt.title("Confusion Matrix - Aspect Classification")

plt.xlabel("Predicted Label")

plt.ylabel("Actual Label")

plt.tight_layout()

plt.show()

# =====================================================
# SIMPAN HASIL PREDIKSI
# =====================================================

results = pd.DataFrame({

    "Sentence": X_test["Reviews"].values,

    "Actual Aspect": actual_labels,

    "Predicted Aspect": predicted_labels

})

results.to_csv(
    "aspect_prediction_results.csv",
    index=False
)

# =====================================================
# SIMPAN DATA YANG SALAH PREDIKSI
# =====================================================

errors = results[
    results["Actual Aspect"] != results["Predicted Aspect"]
]

errors.to_csv(
    "aspect_misclassified.csv",
    index=False
)

print("\nJumlah data test :", len(results))
print("Jumlah prediksi benar :", (results["Actual Aspect"] == results["Predicted Aspect"]).sum())
print("Jumlah prediksi salah :", len(errors))

print("\nFile yang berhasil disimpan:")
print("- classification_report_aspect.csv")
print("- aspect_prediction_results.csv")
print("- aspect_misclassified.csv")

import matplotlib.pyplot as plt
import pandas as pd

# Ekstrak log dari trainer
log_history = trainer.state.log_history

# Filter log untuk training loss dan validation loss
train_losses = []
val_losses = []
steps = []

for log in log_history:
    if 'loss' in log: # Training loss
        train_losses.append(log['loss'])
        steps.append(log['step'])
    if 'eval_loss' in log: # Validation loss
        val_losses.append(log['eval_loss'])

# Pastikan jumlah elemen sama untuk plotting, atau sesuaikan jika ada perbedaan
# Biasanya eval_loss akan muncul setiap 'eval_strategy', jadi mungkin ada perbedaan jumlah
# Jika jumlahnya berbeda, kita bisa membuat x-axis terpisah atau menginterpolasi

# Untuk mempermudah, kita akan menggunakan 'step' untuk x-axis training loss
# Dan 'epoch' (atau setiap 1 eval_step) untuk validation loss

# Ambil step untuk eval_loss (biasanya pada akhir epoch)
# Asumsi eval_strategy="epoch", jadi eval_loss muncul per epoch
epochs_for_val = [log['epoch'] for log in log_history if 'eval_loss' in log]

plt.figure(figsize=(10, 6))
plt.plot(steps[:len(train_losses)], train_losses, label='Training Loss', marker='o', markersize=4, linestyle='-')
plt.plot(epochs_for_val, val_losses, label='Validation Loss', marker='x', markersize=6, linestyle='--')

plt.title('Training and Validation Loss Over Steps/Epochs')
plt.xlabel('Step/Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import os

# Definisikan direktori penyimpanan
output_dir = './aspect_model'

# Pastikan direktori ada, jika tidak, buatlah
if not os.path.exists(output_dir):
    os.makedirs(output_dir)
    print(f"Direktori '{output_dir}' berhasil dibuat.")
else:
    print(f"Direktori '{output_dir}' sudah ada.")

# Simpan model
trainer.save_model(output_dir)
print(f"Model berhasil disimpan ke '{output_dir}'")

# Simpan tokenizer
tokenizer.save_pretrained(output_dir)
print(f"Tokenizer berhasil disimpan ke '{output_dir}'")

# Tampilkan daftar file yang tersimpan
print(f"\nDaftar file yang tersimpan di '{output_dir}':")
for filename in os.listdir(output_dir):
    print(f"- {filename}")

import pandas as pd

# Gabungkan X_test (fitur) dan y_aspect_test (label aspek) ke dalam satu DataFrame
# Pastikan indeks cocok saat menggabungkan
data_test_combined = X_test.copy()
data_test_combined['Aspect'] = y_aspect_test

# Jika Anda juga ingin menyertakan sentimen, dan memiliki y_sentiment_test, bisa ditambahkan juga
# Namun, berdasarkan kode sebelumnya, hanya y_aspect yang dipisahkan secara eksplisit

# Simpan DataFrame ke file CSV
data_test_combined.to_csv('data_test.csv', index=False)

print("Data test berhasil disimpan ke 'data_test.csv'")
print(f"Jumlah baris data test: {len(data_test_combined)}")
print("5 baris pertama dari data_test.csv:")
print(data_test_combined.head())

import shutil

# Nama file output dan folder yang akan di-zip
output_filename = 'aspect_model'
dir_name = './aspect_model'

# Melakukan kompresi
shutil.make_archive(output_filename, 'zip', dir_name)

print(f"File '{output_filename}.zip' berhasil dibuat!")