# -*- coding: utf-8 -*-
"""SentimentClassification8020.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NMtJGWEk1FmxRbhDATIru02l4N_eoXg0
"""

import pandas as pd

# Memuat dataset CSV
df = pd.read_csv('/content/SteamDatasetTiga.csv')

# Menampilkan 5 baris pertama dari dataset
df.head()

print("Total Aspek:")
print(df['Aspect'].value_counts())

print("\nTotal Sentimen:")
# Sentiment positif
positive_sentiment = df[df['Sentiment'] == 'Positif'].shape[0]
print(f"Sentimen Positif: {positive_sentiment}")

# Sentiment negatif
negative_sentiment = df[df['Sentiment'] == 'Negatif'].shape[0]
print(f"Sentimen Negatif: {negative_sentiment}")

sentiment_distribution = pd.crosstab(df['Aspect'], df['Sentiment'])
print("Distribusi Sentimen per Aspek:")
print(sentiment_distribution)

import matplotlib.pyplot as plt

# Memastikan kolom sentimen ada, jika tidak ada, tambahkan dengan 0
# Ini penting jika ada aspek yang tidak memiliki 'Negatif' atau 'Positif'
for col in ['Positif', 'Negatif']: # Assuming only these two sentiments for visualization
    if col not in sentiment_distribution.columns:
        sentiment_distribution[col] = 0

# Buat bar chart stacked
sentiment_distribution[['Positif', 'Negatif']].plot(kind='bar', stacked=True, figsize=(10, 6))
plt.title('Distribusi Sentimen per Aspek')
plt.xlabel('Aspek')
plt.ylabel('Jumlah')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Sentimen')
plt.tight_layout()
plt.show()

from sklearn.model_selection import train_test_split

# 1. Pembersihan Data & Encoding Label
# Menghapus spasi tambahan dan memastikan mapping tepat
df['Sentiment'] = df['Sentiment'].str.strip()
df['label'] = df['Sentiment'].map({'Positif': 0, 'Negatif': 1})

# Menghapus baris yang memiliki nilai NaN di kolom label atau text
df = df.dropna(subset=['label', 'Reviews', 'Aspect']).reset_index(drop=True)

# 2. Membuat input format IndoBERT: Review [SEP] Aspect
df['text_input'] = df['Reviews'].astype(str) + " [SEP] " + df['Aspect'].astype(str)

# 3. Pembagian dataset (Stratified Split)
# Pertama, pisahkan 80% untuk training dan 20% sisanya
train_df, temp_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    stratify=df['label']
)

# Kedua, bagi 20% sisa tadi menjadi validasi (10%) dan testing (10%)
val_df, test_df = train_test_split(
    temp_df,
    test_size=0.5,
    random_state=42,
    stratify=temp_df['label']
)

# Menampilkan hasil pembagian
print(f"Jumlah Data Training  : {len(train_df)} ({len(train_df)/len(df)*100:.0f}%)")
print(f"Jumlah Data Validation: {len(val_df)} ({len(val_df)/len(df)*100:.0f}%)")
print(f"Jumlah Data Testing   : {len(test_df)} ({len(test_df)/len(df)*100:.0f}%)")

# Contoh tampilan data input
print("\nContoh Input IndoBERT:")
print(train_df[['text_input', 'label']].head())

import torch
from torch.utils.data import Dataset
from transformers import AutoTokenizer

# 1. Inisialisasi Tokenizer
model_name = 'indobenchmark/indobert-base-p1'
tokenizer = AutoTokenizer.from_pretrained(model_name)

# 2. Definisi PyTorch Dataset
class SentimentDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=128):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, item):
        # Memastikan teks adalah string
        text = str(self.texts[item])
        label = self.labels[item]

        # Menggunakan __call__ yang lebih fleksibel
        encoding = self.tokenizer(
            text,
            add_special_tokens=True,
            max_length=self.max_len,
            padding='max_length',
            truncation=True,
            return_attention_mask=True,
            return_tensors='pt',
        )

        return {
            'input_ids': encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'labels': torch.tensor(label, dtype=torch.long)
        }

# 3. Persiapan Data
train_dataset = SentimentDataset(train_df['text_input'].to_numpy(), train_df['label'].to_numpy(), tokenizer)
val_dataset = SentimentDataset(val_df['text_input'].to_numpy(), val_df['label'].to_numpy(), tokenizer)
test_dataset = SentimentDataset(test_df['text_input'].to_numpy(), test_df['label'].to_numpy(), tokenizer)

print("Dataset PyTorch berhasil diperbarui.")

import numpy as np
from transformers import (
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

# ==========================
# 1. Load Model
# ==========================
model = AutoModelForSequenceClassification.from_pretrained(
    "indobenchmark/indobert-base-p1",
    num_labels=2,
    ignore_mismatched_sizes=True
)

# ==========================
# 2. Evaluation Metrics
# ==========================
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        predictions,
        average="weighted"
    )

    accuracy = accuracy_score(labels, predictions)

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

# ==========================
# 3. Training Arguments
# ==========================
training_args = TrainingArguments(
    output_dir="./sentiment_result",
    # Menghapus overwrite_output_dir karena menyebabkan TypeError
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    weight_decay=0.01,
    warmup_steps=100,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,
    logging_dir="./logs",
    logging_steps=10,
    report_to="none",
    seed=42
)

# ==========================
# 4. Trainer
# ==========================
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
)

# ==========================
# 5. Fine-tuning
# ==========================
print("=" * 50)
print("Memulai Fine-tuning Sentiment Classification...")
print("=" * 50)

trainer.train()

print("\nFine-tuning selesai!")

# ==========================
# 6. Evaluasi Validation
# ==========================
val_result = trainer.evaluate()

print("\n=== Validation Result ===")
for key, value in val_result.items():
    print(f"{key}: {value:.4f}" if isinstance(value, float) else f"{key}: {value}")

# ==========================
# 7. Evaluasi Test
# ==========================
test_result = trainer.evaluate(test_dataset)

print("\n=== Test Result ===")
for key, value in test_result.items():
    print(f"{key}: {value:.4f}" if isinstance(value, float) else f"{key}: {value}")

# ==========================
# 8. Simpan Model
# ==========================
trainer.save_model("./best_sentiment_model")
tokenizer.save_pretrained("./best_sentiment_model")

print("\nModel berhasil disimpan di folder 'best_sentiment_model'")

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# 1. Mendapatkan prediksi dari model untuk test_dataset
print("Mengambil prediksi untuk data testing...")
raw_pred, labels, _ = trainer.predict(test_dataset)
predictions = np.argmax(raw_pred, axis=1)

# 2. Membuat Confusion Matrix
cm = confusion_matrix(labels, predictions)

# 3. Visualisasi menggunakan Seaborn Heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Positif (0)', 'Negatif (1)'],
            yticklabels=['Positif (0)', 'Negatif (1)'])

plt.title('Confusion Matrix - Sentiment Classification')
plt.xlabel('Prediksi')
plt.ylabel('Label Asli')
plt.show()

# 4. Menampilkan Classification Report untuk detail Precision, Recall, F1
print("\nClassification Report:")
print(classification_report(labels, predictions, target_names=['Positif', 'Negatif']))

import matplotlib.pyplot as plt
import pandas as pd

# Mengambil log history dari trainer
log_history = trainer.state.log_history

# Filter log untuk metrik evaluasi (validation loss)
# Kita mencari entri di mana 'eval_loss' ada
eval_logs = [log for log in log_history if 'eval_loss' in log and 'epoch' in log]

if not eval_logs:
    print("Tidak ada data 'eval_loss' ditemukan dalam log history.")
else:
    # Ekstrak epoch dan eval_loss
    epochs = [log['epoch'] for log in eval_logs]
    validation_losses = [log['eval_loss'] for log in eval_logs]

    # Membuat DataFrame untuk memudahkan plotting
    df_history = pd.DataFrame({
        'Epoch': epochs,
        'Validation Loss': validation_losses
    })

    # Plotting
    plt.figure(figsize=(10, 6))
    plt.plot(df_history['Epoch'], df_history['Validation Loss'], marker='o', linestyle='-', color='b')
    plt.title('Validation Loss per Epoch')
    plt.xlabel('Epoch')
    plt.ylabel('Validation Loss')
    plt.grid(True)
    plt.xticks(df_history['Epoch'])
    plt.tight_layout()
    plt.show()

import pandas as pd
import numpy as np

# 1. Melakukan prediksi pada test_dataset
print("Melakukan prediksi pada data testing...")
raw_pred, labels, _ = trainer.predict(test_dataset)
predictions = np.argmax(raw_pred, axis=1)

# 2. Membuat DataFrame hasil
# Kita mengambil data asli dari test_df yang sudah dipisah sebelumnya
export_df = test_df[['Reviews', 'Aspect', 'Sentiment']].copy()

# Menambahkan kolom prediksi
# Mapping 0 ke 'Positif' dan 1 ke 'Negatif'
mapping = {0: 'Positif', 1: 'Negatif'}
export_df['Predicted Sentiment'] = [mapping[p] for p in predictions]

# Mengganti nama kolom agar sesuai permintaan
export_df.columns = ['Review', 'Aspect', 'Actual Sentiment', 'Predicted Sentiment']

# 3. Simpan ke CSV
output_path = 'hasil_prediksi_sentiment.csv'
export_df.to_csv(output_path, index=False)

print(f"Berhasil menyimpan {len(export_df)} baris ke {output_path}")

# Tampilkan beberapa baris pertama
display(export_df.head())

import pandas as pd
import numpy as np

# 1. Melakukan prediksi pada data testing
raw_pred, labels, _ = trainer.predict(test_dataset)
predictions = np.argmax(raw_pred, axis=1)

# 2. Membuat DataFrame perbandingan
# Mengambil data asli dari test_df
comparison_df = test_df[['Reviews', 'Aspect', 'Sentiment']].copy()
comparison_df['Actual_Label_Idx'] = labels
comparison_df['Predicted_Label_Idx'] = predictions

# 3. Filter data yang salah prediksi (Actual != Predicted)
misclassified_df = comparison_df[comparison_df['Actual_Label_Idx'] != comparison_df['Predicted_Label_Idx']].copy()

# Mapping angka ke teks label untuk kemudahan pembacaan
mapping = {0: 'Positif', 1: 'Negatif'}
misclassified_df['Predicted Sentiment'] = misclassified_df['Predicted_Label_Idx'].map(mapping)

# 4. Memilih dan merapikan kolom sesuai permintaan
final_error_df = misclassified_df[['Reviews', 'Aspect', 'Sentiment', 'Predicted Sentiment']]
final_error_df.columns = ['Review', 'Aspect', 'Actual Sentiment', 'Predicted Sentiment']

# 5. Simpan ke CSV
output_file = 'salah_prediksi_sentiment.csv'
final_error_df.to_csv(output_file, index=False)

print(f"Terdapat {len(final_error_df)} data yang salah diprediksi.")
print(f"File berhasil disimpan sebagai: {output_file}")

# Menampilkan data yang salah (jika ada)
final_error_df.head()

import os

# 1. Menentukan nama folder penyimpanan
save_path = "sentiment_model"

# 2. Membuat folder jika belum ada (opsional, save_model otomatis membuatnya)
if not os.path.exists(save_path):
    os.makedirs(save_path)

# 3. Menyimpan model menggunakan Trainer
# Ini akan menyimpan config.json dan model.safetensors / pytorch_model.bin
trainer.save_model(save_path)

# 4. Menyimpan tokenizer
# Ini akan menyimpan tokenizer_config.json, vocab.txt, tokenizer.json, dll.
tokenizer.save_pretrained(save_path)

print(f"Model dan tokenizer berhasil disimpan di folder: {save_path}")
print("-" * 30)

# 5. Menampilkan daftar file yang tersimpan untuk memastikan kelengkapan
files_in_dir = os.listdir(save_path)
print(f"Daftar file di dalam '{save_path}':")
for file in sorted(files_in_dir):
    print(f"- {file}")

import shutil
import os

# 1. Menentukan nama folder sumber dan nama file zip output
folder_name = 'sentiment_model'
output_zip = 'sentiment_model'

# 2. Melakukan kompresi folder menjadi .zip
if os.path.exists(folder_name):
    shutil.make_archive(output_zip, 'zip', folder_name)
    print(f"Berhasil mengompres folder '{folder_name}' menjadi '{output_zip}.zip'")
else:
    print(f"Error: Folder '{folder_name}' tidak ditemukan.")